fastq_dir: "/maps/projects/renlab/people/qgr178/Projects/AGO1/Data"
fastqc_dir: "/maps/projects/renlab/people/qgr178/Projects/AGO1/fastqc"
multiqc_dir: "/maps/projects/renlab/people/qgr178/Projects/AGO1/multiqc"
extension: "fq.gz"  # Change to "fastq.gz" if needed